### ISSUE TITLE
Avoid duplicate tables and graphics

### ISSUE THREAD

**Issue by jenswaeckerle** [yihui/rolldown#18]
I just tried rolldown and it looks very interesting! I was just wondering if it was possible to not show tables and graphics twice (in the sidebar section on the left and the main section on the right). Essentially, I would like to have only the text on the left and the media (tables, graphs, videos) on the right.

Is this possible?

Thank you so much for your help!
Best,
Jens

**Comment by jdbarillas** [comment]
I added CSS within my Rmd file to do something similar to what you're asking

```
.sidebar img, .sidebar .caption {
  display: none;
}
```

You can see the full Rmd file here https://github.com/jdbarillas/rolldown_demo/blob/master/top_anime.Rmd

And output here https://twitter.com/jdbarillas/status/1121119611502714880?s=20

**Comment by jenswaeckerle** [comment]
Thank you very much, that is excatly what I needed!
